export const home = [
    {
        name: "ROBOWARS",
        cardBg: "./Images/Robowars.png",
        cardBorder: "solid 5px #e37430",
        cardBoxShadow: "0 0 15px 3px #e37430",
        dateColor: "#ffffff",
        date: "04",
    },
    {
        name: "BRAINWIZ",
        cardBg: "./Images/Brainwiz.png",
        cardBorder: "solid 5px #213555",
        cardBoxShadow: "0 0 15px 3px #213555",
        dateColor: "#213555",
        date: "04",
    },
    {
        name: "YOUTH TECH-TIC",
        cardBg: "./Images/YTT-bg.png",
        cardBorder: "solid 5px #2B4A59",
        cardBoxShadow: "0 0 15px 3px #2B4A59",
        dateColor: "#2B4A59",
        date: "04",
    },
    {
        name: "GAMEJAM",
        cardBg: "./Images/coming_soon_mobile.png",
        cardBorder: "solid 5px #190051",
        cardBoxShadow: "0 0 15px 3px #190051",
        dateColor: "#05BECA",
        date: "04",
    },
    {
        name: "COMING SOON",
        cardBg: "./Images/coming_soon_mobile.png",
        cardBorder: "solid 5px #d321a3",
        cardBoxShadow: "0 0 15px 3px #d321a3",
        dateColor: "#ffffff",
        date: "xx",
    },
    {
        name: "COMING SOON",
        cardBg: "./Images/coming_soon_mobile.png",
        cardBorder: "solid 5px #d321a3",
        cardBoxShadow: "0 0 15px 3px #d321a3",
        dateColor: "#ffffff",
        date: "xx",
    },
];